openapi: 3.0.3
info:
  title: My Bookshop
  version: '1.0'
paths:
  /books/{genre}/{year}:
    get:
      operationId: getBooksGenreYear
      parameters:
      - name: genre
        in: path
        required: true
        schema:
          type: string
      - name: year
        in: path
        required: true
        schema:
          type: integer
      - name: limit
        in: query
        description: Maximum number of books to retrieve
        required: true
        schema:
          type: integer
      - name: X-Auth-Token
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '400':
          description: 'Invalid value for: path parameter year, Invalid value for:
            query parameter limit, Invalid value for: header X-Auth-Token'
          content:
            text/plain:
              schema:
                type: string
        default:
          description: ''
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Book:
      required:
      - title
      type: object
      properties:
        title:
          type: string
